name: Run Ruff Linter

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo add-apt-repository ppa:ettusresearch/uhd
          sudo apt update
          sudo apt install -y \
            fftw-dev \
            libboost-all-dev \
            libuhd-dev \
            uhd-host \
            libairspy-dev \
            libhackrf-dev \
            cmake \
            build-essential

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Run ruff linter
        run: |
          uv run ruff check .